version: '3'

services:

  api-server:
    image: ${NCP_CONTAINER_REGISTRY_BATCH}/payout-batch
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FMP_API_KEY: ${FMP_API_KEY}
    restart: always
