spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/nexters
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true