spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexters
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/nexters
    user: test
    password: test
    baseline-version: 0
