spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexters
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
