schedules:
  cron:
    dividend: "0 0 0 * * *"

financial:
  fmp:
    api-key: ${FMP_API_KEY}
    base-url: https://financialmodelingprep.com
    stock-list-path: /api/v3/stock/list
    exchange-symbols-stock-list-path: /api/v3/symbol/
    stock-screener-path: /api/v3/stock-screener
    stock-dividend-calender-path: "/api/v3/stock_dividend_calendar"