schedules:
  cron:
    dividend: "0 0 0 * * *"

financial:
  fmp:
    key: ${FMP_API_KEY}
    base-url: "https://financialmodelingprep.com"
    stock-dividend-calendar-postfix: "/api/v3/stock_dividend_calendar"