springdoc:
  swagger-ui:
    path: /payout-docs.html
    query-config-enabled: true
    enabled: true

financial:
  eodhd:
    base-url: https://eodhd.com
    stock-logo-path: /img/logos/US/
    image-postfix: .png
